const actionType = {
  // ITEMS
  ITEMS_LOADING: 'ITEMS_LOADING',
  ITEMS_ERROR: 'ITEMS_ERROR',
  CLEAR_ITEMS_ERROR: 'ITEMS_ERROR',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',

  // USERS
  USER_LOADING: 'USER_LOADING',
  USER_ERROR: 'USER_ERROR',
  CLEAR_USER_ERROR: 'CLEAR_USER_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
};

export default actionType;
